// -*- mode: kotlin -*-

/*
 * AUTOGENERATED BY glean_parser.  DO NOT EDIT.
 */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

@file:Suppress("PackageNaming")
package com.app.browser_components.service.glean


internal object GleanBaseline {
    /**
     * The duration of the last foreground session.
     */
    val duration: TimespanMetricType by lazy {
        TimespanMetricType(
            name = "duration",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Ping,
            disabled = false,
            timeUnit = TimeUnit.Second
            )
    }

    /**
     * The name of the operating system.
     */
    val os: StringMetricType by lazy {
        StringMetricType(
            name = "os",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * The version of the operating system.
     */
    val osVersion: StringMetricType by lazy {
        StringMetricType(
            name = "os_version",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * The manufacturer of the device the application is running on.
     */
    val deviceManufacturer: StringMetricType by lazy {
        StringMetricType(
            name = "device_manufacturer",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * The model of the device the application is running on.
     */
    val deviceModel: StringMetricType by lazy {
        StringMetricType(
            name = "device_model",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * The architecture of the device, (e.g. "arm", "x86").
     */
    val architecture: StringMetricType by lazy {
        StringMetricType(
            name = "architecture",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * List of accessibility services enabled on the device.
     */
    val a11yServices: StringListMetricType by lazy {
        StringListMetricType(
            name = "a11y_services",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Ping,
            disabled = false
            )
    }

    /**
     * The locale of the application (e.g. "es-ES").
     */
    val locale: StringMetricType by lazy {
        StringMetricType(
            name = "locale",
            category = "glean.baseline",
            sendInPings = listOf("baseline"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }
}
