// -*- mode: kotlin -*-

/*
 * AUTOGENERATED BY glean_parser.  DO NOT EDIT.
 */

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */


package com.app.browser_components.service.glean

internal object GleanInternalMetrics {
    /**
     * A UUID uniquely identifying the client.
     */
    val clientId: UuidMetricType by lazy {
        UuidMetricType(
            name = "client_id",
            category = "",
            sendInPings = listOf("glean_ping_info"),
            lifetime = Lifetime.User,
            disabled = false
            )
    }

    /**
     * The build identifier generated by the CI system (e.g. "1234/A").
     */
    val appBuild: StringMetricType by lazy {
        StringMetricType(
            name = "app_build",
            category = "",
            sendInPings = listOf("glean_ping_info"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }

    /**
     * The user visible version string (e.g. "1.0.3").
     */
    val appDisplayVersion: StringMetricType by lazy {
        StringMetricType(
            name = "app_display_version",
            category = "",
            sendInPings = listOf("glean_ping_info"),
            lifetime = Lifetime.Application,
            disabled = false
            )
    }
}
